/*
 *
 */

package https.www_supernotariado_gov_co.services.bachue.co.enviodocumentos.v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import https.www_supernotariado_gov_co.schemas.bachue.co.enviodocumentos.enviardocumento.v1.ObjectFactory;
import https.www_supernotariado_gov_co.schemas.bachue.co.enviodocumentos.enviardocumento.v1.TipoEntradaEnviarDocumento;
import https.www_supernotariado_gov_co.schemas.bachue.co.enviodocumentos.enviardocumento.v1.TipoSalidaEnviarDocumento;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150120.1832
 * Generated source version: 2.2
 *
 */
@WebService(name = "SUT_CO_EnvioDocumentos", targetNamespace = "https://www.supernotariado.gov.co/services/bachue/co/enviodocumentos/v1")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SUTCOEnvioDocumentos {


    /**
     * Enviar documento.
     *
     * @param entrada the entrada
     * @return     returns https.www_supernotariado_gov_co.schemas.bachue.co.enviodocumentos.enviardocumento.v1.TipoSalidaEnviarDocumento
     */
    @WebMethod(operationName = "EnviarDocumento", action = "https://www.supernotariado.gov.co/services/bachue/co/enviodocumentos/v1/EnviarDocumento")
    @WebResult(name = "salidaEnviarDocumento", targetNamespace = "https://www.supernotariado.gov.co/schemas/bachue/co/enviodocumentos/enviardocumento/v1", partName = "salida")
    public TipoSalidaEnviarDocumento enviarDocumento(
        @WebParam(name = "entradaEnviarDocumento", targetNamespace = "https://www.supernotariado.gov.co/schemas/bachue/co/enviodocumentos/enviardocumento/v1", partName = "entrada")
        TipoEntradaEnviarDocumento entrada);

}
