/*
 *
 */

package https.www_supernotariado_gov_co.services.bachue.co.relacionesdocumento.v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import https.www_supernotariado_gov_co.schemas.bachue.co.relacionesdocumento.relacionardocumento.v1.ObjectFactory;
import https.www_supernotariado_gov_co.schemas.bachue.co.relacionesdocumento.relacionardocumento.v1.TipoEntradaRelacionarDocumento;
import https.www_supernotariado_gov_co.schemas.bachue.co.relacionesdocumento.relacionardocumento.v1.TipoSalidaRelacionarDocumento;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150120.1832
 * Generated source version: 2.2
 *
 */
@WebService(name = "SUT_CO_RelacionesDocumento", targetNamespace = "https://www.supernotariado.gov.co/services/bachue/co/relacionesdocumento/v1")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SUTCORelacionesDocumento {


    /**
     * Relacionar documento.
     *
     * @param entrada the entrada
     * @return     returns https.www_supernotariado_gov_co.schemas.bachue.co.relacionesdocumento.relacionardocumento.v1.TipoSalidaRelacionarDocumento
     */
    @WebMethod(operationName = "RelacionarDocumento", action = "https://www.supernotariado.gov.co/services/bachue/co/relacionesdocumento/v1/RelacionarDocumento")
    @WebResult(name = "salidaRelacionarDocumento", targetNamespace = "https://www.supernotariado.gov.co/schemas/bachue/co/relacionesdocumento/relacionardocumento/v1", partName = "salida")
    public TipoSalidaRelacionarDocumento relacionarDocumento(
        @WebParam(name = "entradaRelacionarDocumento", targetNamespace = "https://www.supernotariado.gov.co/schemas/bachue/co/relacionesdocumento/relacionardocumento/v1", partName = "entrada")
        TipoEntradaRelacionarDocumento entrada);

}
