/*
 *
 */

package https.www_supernotariado_gov_co.services.bachue.co.relacionesdocumento.v1;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150120.1832
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "SUT_CO_RelacionesDocumento", targetNamespace = "https://www.supernotariado.gov.co/services/bachue/co/relacionesdocumento/v1", wsdlLocation = "file:/C:/Users/consultor/Documents/NetbeansProjects82/ClienteOWCC/src/conf/xml-resources/web-services/BeanRelacionDocumento/wsdl/BS_SUT_CO_RelacionesDocumento.wsdl")
public class SUTCORelacionesDocumento_Service
    extends Service
{

    /** The Constant SUTCORELACIONESDOCUMENTO_WSDL_LOCATION. */
    private final static URL SUTCORELACIONESDOCUMENTO_WSDL_LOCATION;

    /** The Constant SUTCORELACIONESDOCUMENTO_EXCEPTION. */
    private final static WebServiceException SUTCORELACIONESDOCUMENTO_EXCEPTION;

    /** The Constant SUTCORELACIONESDOCUMENTO_QNAME. */
    private final static QName SUTCORELACIONESDOCUMENTO_QNAME = new QName("https://www.supernotariado.gov.co/services/bachue/co/relacionesdocumento/v1", "SUT_CO_RelacionesDocumento");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/consultor/Documents/NetbeansProjects82/ClienteOWCC/src/conf/xml-resources/web-services/BeanRelacionDocumento/wsdl/BS_SUT_CO_RelacionesDocumento.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SUTCORELACIONESDOCUMENTO_WSDL_LOCATION = url;
        SUTCORELACIONESDOCUMENTO_EXCEPTION = e;
    }

    /**
     * Instantiates a new SUTCO relaciones documento service.
     */
    public SUTCORelacionesDocumento_Service() {
        super(__getWsdlLocation(), SUTCORELACIONESDOCUMENTO_QNAME);
    }

    /**
     * Instantiates a new SUTCO relaciones documento service.
     *
     * @param features the features
     */
    public SUTCORelacionesDocumento_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), SUTCORELACIONESDOCUMENTO_QNAME, features);
    }

    /**
     * Instantiates a new SUTCO relaciones documento service.
     *
     * @param wsdlLocation the wsdl location
     */
    public SUTCORelacionesDocumento_Service(URL wsdlLocation) {
        super(wsdlLocation, SUTCORELACIONESDOCUMENTO_QNAME);
    }

    /**
     * Instantiates a new SUTCO relaciones documento service.
     *
     * @param wsdlLocation the wsdl location
     * @param features the features
     */
    public SUTCORelacionesDocumento_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SUTCORELACIONESDOCUMENTO_QNAME, features);
    }

    /**
     * Instantiates a new SUTCO relaciones documento service.
     *
     * @param wsdlLocation the wsdl location
     * @param serviceName the service name
     */
    public SUTCORelacionesDocumento_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * Instantiates a new SUTCO relaciones documento service.
     *
     * @param wsdlLocation the wsdl location
     * @param serviceName the service name
     * @param features the features
     */
    public SUTCORelacionesDocumento_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * Gets the SUTCO relaciones documento port.
     *
     * @return     returns SUTCORelacionesDocumento
     */
    @WebEndpoint(name = "SUT_CO_RelacionesDocumentoPort")
    public SUTCORelacionesDocumento getSUTCORelacionesDocumentoPort() {
        return super.getPort(new QName("https://www.supernotariado.gov.co/services/bachue/co/relacionesdocumento/v1", "SUT_CO_RelacionesDocumentoPort"), SUTCORelacionesDocumento.class);
    }

    /**
     * Gets the SUTCO relaciones documento port.
     *
     * @param features     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return     returns SUTCORelacionesDocumento
     */
    @WebEndpoint(name = "SUT_CO_RelacionesDocumentoPort")
    public SUTCORelacionesDocumento getSUTCORelacionesDocumentoPort(WebServiceFeature... features) {
        return super.getPort(new QName("https://www.supernotariado.gov.co/services/bachue/co/relacionesdocumento/v1", "SUT_CO_RelacionesDocumentoPort"), SUTCORelacionesDocumento.class, features);
    }

    /**
     * Gets the wsdl location.
     *
     * @return the url
     */
    private static URL __getWsdlLocation() {
        if (SUTCORELACIONESDOCUMENTO_EXCEPTION!= null) {
            throw SUTCORELACIONESDOCUMENTO_EXCEPTION;
        }
        return SUTCORELACIONESDOCUMENTO_WSDL_LOCATION;
    }

}
