/*
 *
 */

package https.www_supernotariado_gov_co.services.bachue.co.cierreaperturaexpediente.v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import https.www_supernotariado_gov_co.schemas.bachue.co.cierreaperturaexpediente.aperturaturno.v1.TipoEntradaAperturaTurno;
import https.www_supernotariado_gov_co.schemas.bachue.co.cierreaperturaexpediente.aperturaturno.v1.TipoSalidaAperturaTurno;
import https.www_supernotariado_gov_co.schemas.bachue.co.cierreaperturaexpediente.cierreturno.v1.TipoEntradaCierreTurno;
import https.www_supernotariado_gov_co.schemas.bachue.co.cierreaperturaexpediente.cierreturno.v1.TipoSalidaCierreTurno;
import https.www_supernotariado_gov_co.schemas.bachue.co.cierreaperturaexpediente.obtenerindiceelectronico.v1.TipoEntradaObtenerIndiceElectronico;
import https.www_supernotariado_gov_co.schemas.bachue.co.cierreaperturaexpediente.obtenerindiceelectronico.v1.TipoSalidaObtenerIndiceElectronico;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150120.1832
 * Generated source version: 2.2
 *
 */
@WebService(name = "SUT_CO_CierreAperturaExpediente", targetNamespace = "https://www.supernotariado.gov.co/services/bachue/co/cierreaperturaexpediente/v1")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    https.www_supernotariado_gov_co.schemas.bachue.co.cierreaperturaexpediente.aperturaturno.v1.ObjectFactory.class,
    https.www_supernotariado_gov_co.schemas.bachue.co.cierreaperturaexpediente.cierreturno.v1.ObjectFactory.class
})
public interface SUTCOCierreAperturaExpediente {


    /**
     * Cierre turno.
     *
     * @param entrada the entrada
     * @return     returns https.www_supernotariado_gov_co.schemas.bachue.co.cierreaperturaexpediente.cierreturno.v1.TipoSalidaCierreTurno
     */
    @WebMethod(operationName = "CierreTurno", action = "https://www.supernotariado.gov.co/services/bachue/co/cierreaperturaexpediente/v1/CierreTurno")
    @WebResult(name = "salidaCierreTurno", targetNamespace = "https://www.supernotariado.gov.co/schemas/bachue/co/cierreaperturaexpediente/cierreturno/v1", partName = "salida")
    public TipoSalidaCierreTurno cierreTurno(
        @WebParam(name = "entradaCierreTurno", targetNamespace = "https://www.supernotariado.gov.co/schemas/bachue/co/cierreaperturaexpediente/cierreturno/v1", partName = "entrada")
        TipoEntradaCierreTurno entrada);

    /**
     * Apertura turno.
     *
     * @param entrada the entrada
     * @return     returns https.www_supernotariado_gov_co.schemas.bachue.co.cierreaperturaexpediente.aperturaturno.v1.TipoSalidaAperturaTurno
     */
    @WebMethod(operationName = "AperturaTurno", action = "https://www.supernotariado.gov.co/services/bachue/co/cierreaperturaexpediente/v1/AperturaTurno")
    @WebResult(name = "salidaAperturaTurno", targetNamespace = "https://www.supernotariado.gov.co/schemas/bachue/co/cierreaperturaexpediente/aperturaturno/v1", partName = "salida")
    public TipoSalidaAperturaTurno aperturaTurno(
        @WebParam(name = "entradaAperturaTurno", targetNamespace = "https://www.supernotariado.gov.co/schemas/bachue/co/cierreaperturaexpediente/aperturaturno/v1", partName = "entrada")
        TipoEntradaAperturaTurno entrada);

    /**
     * Obteber indice electronico.
     *
     * @param entrada the entrada
     * @return     returns https.www_supernotariado_gov_co.schemas.bachue.co.cierreaperturaexpediente.obtenerindiceelectronico.v1.TipoSalidaObtenerIndiceElectronico
     */
    @WebMethod(operationName = "ObtenerIndiceElectronico", action = "https://www.supernotariado.gov.co/services/bachue/co/cierreaperturaexpediente/v1/ObtenerIndiceElectronico")
    @WebResult(name = "salidaObtenerIndiceElectronico", targetNamespace = "https://www.supernotariado.gov.co/schemas/bachue/co/cierreaperturaexpediente/obtenerindiceelectronico/v1", partName = "salida")
    public TipoSalidaObtenerIndiceElectronico obtenerIndiceElectronico(
        @WebParam(name = "entradaObtenerIndiceElectronico", targetNamespace = "https://www.supernotariado.gov.co/schemas/bachue/co/cierreaperturaexpediente/obtenerindiceelectronico/v1", partName = "entrada")
        TipoEntradaObtenerIndiceElectronico entrada);

}
