/*
 *
 */

package https.www_supernotariado_gov_co.services.bachue.co.cierreaperturaexpediente.v1;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150120.1832
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "SUT_CO_CierreAperturaExpediente", targetNamespace = "https://www.supernotariado.gov.co/services/bachue/co/cierreaperturaexpediente/v1", wsdlLocation = "file:/C:/Users/consultor/Documents/NetbeansProjects82/ClienteOWCC/src/conf/xml-resources/web-services/beanExpediente/wsdl/SUT_CO_CierreAperturaExpediente.wsdl")
public class SUTCOCierreAperturaExpediente_Service
    extends Service
{

    /** The Constant SUTCOCIERREAPERTURAEXPEDIENTE_WSDL_LOCATION. */
    private final static URL SUTCOCIERREAPERTURAEXPEDIENTE_WSDL_LOCATION;

    /** The Constant SUTCOCIERREAPERTURAEXPEDIENTE_EXCEPTION. */
    private final static WebServiceException SUTCOCIERREAPERTURAEXPEDIENTE_EXCEPTION;

    /** The Constant SUTCOCIERREAPERTURAEXPEDIENTE_QNAME. */
    private final static QName SUTCOCIERREAPERTURAEXPEDIENTE_QNAME = new QName("https://www.supernotariado.gov.co/services/bachue/co/cierreaperturaexpediente/v1", "SUT_CO_CierreAperturaExpediente");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/consultor/Documents/NetbeansProjects82/ClienteOWCC/src/conf/xml-resources/web-services/beanExpediente/wsdl/SUT_CO_CierreAperturaExpediente.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SUTCOCIERREAPERTURAEXPEDIENTE_WSDL_LOCATION = url;
        SUTCOCIERREAPERTURAEXPEDIENTE_EXCEPTION = e;
    }

    /**
     * Instantiates a new SUTCO cierre apertura expediente service.
     */
    public SUTCOCierreAperturaExpediente_Service() {
        super(__getWsdlLocation(), SUTCOCIERREAPERTURAEXPEDIENTE_QNAME);
    }

    /**
     * Instantiates a new SUTCO cierre apertura expediente service.
     *
     * @param features the features
     */
    public SUTCOCierreAperturaExpediente_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), SUTCOCIERREAPERTURAEXPEDIENTE_QNAME, features);
    }

    /**
     * Instantiates a new SUTCO cierre apertura expediente service.
     *
     * @param wsdlLocation the wsdl location
     */
    public SUTCOCierreAperturaExpediente_Service(URL wsdlLocation) {
        super(wsdlLocation, SUTCOCIERREAPERTURAEXPEDIENTE_QNAME);
    }

    /**
     * Instantiates a new SUTCO cierre apertura expediente service.
     *
     * @param wsdlLocation the wsdl location
     * @param features the features
     */
    public SUTCOCierreAperturaExpediente_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SUTCOCIERREAPERTURAEXPEDIENTE_QNAME, features);
    }

    /**
     * Instantiates a new SUTCO cierre apertura expediente service.
     *
     * @param wsdlLocation the wsdl location
     * @param serviceName the service name
     */
    public SUTCOCierreAperturaExpediente_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * Instantiates a new SUTCO cierre apertura expediente service.
     *
     * @param wsdlLocation the wsdl location
     * @param serviceName the service name
     * @param features the features
     */
    public SUTCOCierreAperturaExpediente_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * Gets the SUTCO cierre apertura expediente port.
     *
     * @return     returns SUTCOCierreAperturaExpediente
     */
    @WebEndpoint(name = "SUT_CO_CierreAperturaExpedientePort")
    public SUTCOCierreAperturaExpediente getSUTCOCierreAperturaExpedientePort() {
        return super.getPort(new QName("https://www.supernotariado.gov.co/services/bachue/co/cierreaperturaexpediente/v1", "SUT_CO_CierreAperturaExpedientePort"), SUTCOCierreAperturaExpediente.class);
    }

    /**
     * Gets the SUTCO cierre apertura expediente port.
     *
     * @param features     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return     returns SUTCOCierreAperturaExpediente
     */
    @WebEndpoint(name = "SUT_CO_CierreAperturaExpedientePort")
    public SUTCOCierreAperturaExpediente getSUTCOCierreAperturaExpedientePort(WebServiceFeature... features) {
        return super.getPort(new QName("https://www.supernotariado.gov.co/services/bachue/co/cierreaperturaexpediente/v1", "SUT_CO_CierreAperturaExpedientePort"), SUTCOCierreAperturaExpediente.class, features);
    }

    /**
     * Gets the wsdl location.
     *
     * @return the url
     */
    private static URL __getWsdlLocation() {
        if (SUTCOCIERREAPERTURAEXPEDIENTE_EXCEPTION!= null) {
            throw SUTCOCIERREAPERTURAEXPEDIENTE_EXCEPTION;
        }
        return SUTCOCIERREAPERTURAEXPEDIENTE_WSDL_LOCATION;
    }

}
