/*
 *
 */

package https.www_supernotariado_gov_co.services.bachue.co.busquedadocumentos.v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import https.www_supernotariado_gov_co.schemas.bachue.co.busquedadocumentos.consultar.v1.TipoEntradaConsultar;
import https.www_supernotariado_gov_co.schemas.bachue.co.busquedadocumentos.consultar.v1.TipoSalidaConsultar;
import https.www_supernotariado_gov_co.schemas.bachue.co.busquedadocumentos.obtenerarchivo.v1.TipoEntradaObtenerArchivo;
import https.www_supernotariado_gov_co.schemas.bachue.co.busquedadocumentos.obtenerarchivo.v1.TipoSalidaObtenerArchivo;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150120.1832
 * Generated source version: 2.2
 *
 */
@WebService(name = "SUT_CO_BusquedaDocumentos", targetNamespace = "https://www.supernotariado.gov.co/services/bachue/co/busquedadocumentos/v1")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    https.www_supernotariado_gov_co.schemas.bachue.co.busquedadocumentos.consultar.v1.ObjectFactory.class,
    https.www_supernotariado_gov_co.schemas.bachue.co.busquedadocumentos.obtenerarchivo.v1.ObjectFactory.class
})
public interface SUTCOBusquedaDocumentos {


    /**
     * Consultar.
     *
     * @param entrada the entrada
     * @return     returns https.www_supernotariado_gov_co.schemas.bachue.co.busquedadocumentos.consultar.v1.TipoSalidaConsultar
     */
    @WebMethod(operationName = "Consultar", action = "https://www.supernotariado.gov.co/services/bachue/co/busquedadocumentos/v1/Consultar")
    @WebResult(name = "salidaConsultar", targetNamespace = "https://www.supernotariado.gov.co/schemas/bachue/co/busquedadocumentos/consultar/v1", partName = "salida")
    public TipoSalidaConsultar consultar(
        @WebParam(name = "entradaConsultar", targetNamespace = "https://www.supernotariado.gov.co/schemas/bachue/co/busquedadocumentos/consultar/v1", partName = "entrada")
        TipoEntradaConsultar entrada);

    /**
     * Obtener archivo.
     *
     * @param entrada the entrada
     * @return     returns https.www_supernotariado_gov_co.schemas.bachue.co.busquedadocumentos.obtenerarchivo.v1.TipoSalidaObtenerArchivo
     */
    @WebMethod(operationName = "ObtenerArchivo", action = "https://www.supernotariado.gov.co/services/bachue/co/busquedadocumentos/v1/ObtenerArchivo")
    @WebResult(name = "salidaObtenerArchivo", targetNamespace = "https://www.supernotariado.gov.co/schemas/bachue/co/busquedadocumentos/obtenerarchivo/v1", partName = "salida")
    public TipoSalidaObtenerArchivo obtenerArchivo(
        @WebParam(name = "entradaObtenerArchivo", targetNamespace = "https://www.supernotariado.gov.co/schemas/bachue/co/busquedadocumentos/obtenerarchivo/v1", partName = "entrada")
        TipoEntradaObtenerArchivo entrada);

}
