/*
 *
 */

package https.www_supernotariado_gov_co.services.bachue.co.busquedadocumentos.v1;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150120.1832
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "SUT_CO_BusquedaDocumentos", targetNamespace = "https://www.supernotariado.gov.co/services/bachue/co/busquedadocumentos/v1", wsdlLocation = "file:/C:/Users/consultor/Documents/NetbeansProjects82/ClienteOWCC/src/conf/xml-resources/web-services/beanBuscar/wsdl/BS_SUT_CO_BusquedaDocumentos.wsdl")
public class SUTCOBusquedaDocumentos_Service
    extends Service
{

    /** The Constant SUTCOBUSQUEDADOCUMENTOS_WSDL_LOCATION. */
    private final static URL SUTCOBUSQUEDADOCUMENTOS_WSDL_LOCATION;

    /** The Constant SUTCOBUSQUEDADOCUMENTOS_EXCEPTION. */
    private final static WebServiceException SUTCOBUSQUEDADOCUMENTOS_EXCEPTION;

    /** The Constant SUTCOBUSQUEDADOCUMENTOS_QNAME. */
    private final static QName SUTCOBUSQUEDADOCUMENTOS_QNAME = new QName("https://www.supernotariado.gov.co/services/bachue/co/busquedadocumentos/v1", "SUT_CO_BusquedaDocumentos");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/consultor/Documents/NetbeansProjects82/ClienteOWCC/src/conf/xml-resources/web-services/beanBuscar/wsdl/BS_SUT_CO_BusquedaDocumentos.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SUTCOBUSQUEDADOCUMENTOS_WSDL_LOCATION = url;
        SUTCOBUSQUEDADOCUMENTOS_EXCEPTION = e;
    }

    /**
     * Instantiates a new SUTCO busqueda documentos service.
     */
    public SUTCOBusquedaDocumentos_Service() {
        super(__getWsdlLocation(), SUTCOBUSQUEDADOCUMENTOS_QNAME);
    }

    /**
     * Instantiates a new SUTCO busqueda documentos service.
     *
     * @param features the features
     */
    public SUTCOBusquedaDocumentos_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), SUTCOBUSQUEDADOCUMENTOS_QNAME, features);
    }

    /**
     * Instantiates a new SUTCO busqueda documentos service.
     *
     * @param wsdlLocation the wsdl location
     */
    public SUTCOBusquedaDocumentos_Service(URL wsdlLocation) {
        super(wsdlLocation, SUTCOBUSQUEDADOCUMENTOS_QNAME);
    }

    /**
     * Instantiates a new SUTCO busqueda documentos service.
     *
     * @param wsdlLocation the wsdl location
     * @param features the features
     */
    public SUTCOBusquedaDocumentos_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SUTCOBUSQUEDADOCUMENTOS_QNAME, features);
    }

    /**
     * Instantiates a new SUTCO busqueda documentos service.
     *
     * @param wsdlLocation the wsdl location
     * @param serviceName the service name
     */
    public SUTCOBusquedaDocumentos_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * Instantiates a new SUTCO busqueda documentos service.
     *
     * @param wsdlLocation the wsdl location
     * @param serviceName the service name
     * @param features the features
     */
    public SUTCOBusquedaDocumentos_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * Gets the SUTCO busqueda documentos port.
     *
     * @return     returns SUTCOBusquedaDocumentos
     */
    @WebEndpoint(name = "SUT_CO_BusquedaDocumentosPort")
    public SUTCOBusquedaDocumentos getSUTCOBusquedaDocumentosPort() {
        return super.getPort(new QName("https://www.supernotariado.gov.co/services/bachue/co/busquedadocumentos/v1", "SUT_CO_BusquedaDocumentosPort"), SUTCOBusquedaDocumentos.class);
    }

    /**
     * Gets the SUTCO busqueda documentos port.
     *
     * @param features     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return     returns SUTCOBusquedaDocumentos
     */
    @WebEndpoint(name = "SUT_CO_BusquedaDocumentosPort")
    public SUTCOBusquedaDocumentos getSUTCOBusquedaDocumentosPort(WebServiceFeature... features) {
        return super.getPort(new QName("https://www.supernotariado.gov.co/services/bachue/co/busquedadocumentos/v1", "SUT_CO_BusquedaDocumentosPort"), SUTCOBusquedaDocumentos.class, features);
    }

    /**
     * Gets the wsdl location.
     *
     * @return the url
     */
    private static URL __getWsdlLocation() {
        if (SUTCOBUSQUEDADOCUMENTOS_EXCEPTION!= null) {
            throw SUTCOBUSQUEDADOCUMENTOS_EXCEPTION;
        }
        return SUTCOBUSQUEDADOCUMENTOS_WSDL_LOCATION;
    }

}
