
package https.www_supernotariado_gov_co.services.bachue.co.actualizacionmetadatospoderes.v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import https.www_supernotariado_gov_co.schemas.bachue.co.actualizacionmetadatospoderes.actualizarmetadatospoder.v1.ObjectFactory;
import https.www_supernotariado_gov_co.schemas.bachue.co.actualizacionmetadatospoderes.actualizarmetadatospoder.v1.TipoEntradaActualizarMetadatosPoder;
import https.www_supernotariado_gov_co.schemas.bachue.co.actualizacionmetadatospoderes.actualizarmetadatospoder.v1.TipoSalidaActualizarMetadatosPoder;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150120.1832
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BS_SAN_CO_ActualizacionMetadatosPoderes", targetNamespace = "https://www.supernotariado.gov.co/services/bachue/co/actualizacionmetadatospoderes/v1")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BSSANCOActualizacionMetadatosPoderes {


    /**
     * 
     * @param entrada
     * @return
     *     returns https.www_supernotariado_gov_co.schemas.bachue.co.actualizacionmetadatospoderes.actualizarmetadatospoder.v1.TipoSalidaActualizarMetadatosPoder
     */
    @WebMethod(operationName = "ActualizarMetadatosPoder", action = "https://www.supernotariado.gov.co/services/bachue/co/actualizacionmetadatospoderes/v1/ActualizarMetadatosPoder")
    @WebResult(name = "salidaActualizarMetadatosPoder", targetNamespace = "https://www.supernotariado.gov.co/schemas/bachue/co/actualizacionmetadatospoderes/actualizarmetadatospoder/v1", partName = "salida")
    public TipoSalidaActualizarMetadatosPoder actualizarMetadatosPoder(
        @WebParam(name = "entradaActualizarMetadatosPoder", targetNamespace = "https://www.supernotariado.gov.co/schemas/bachue/co/actualizacionmetadatospoderes/actualizarmetadatospoder/v1", partName = "entrada")
        TipoEntradaActualizarMetadatosPoder entrada);

}
