
package https.www_supernotariado_gov_co.services.bachue.co.actualizacionmetadatospoderes.v1;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150120.1832
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BS_SAN_CO_ActualizacionMetadatosPoderes", targetNamespace = "https://www.supernotariado.gov.co/services/bachue/co/actualizacionmetadatospoderes/v1", wsdlLocation = "file:/C:/Users/consultor/Documents/NetbeansProjects82/ClienteOWCC/src/conf/xml-resources/web-services/BeanActualizarMetaPoder/wsdl/BS_SAN_CO_ActualizacionMetadatosPoderes.wsdl")
public class BSSANCOActualizacionMetadatosPoderes_Service
    extends Service
{

    private final static URL BSSANCOACTUALIZACIONMETADATOSPODERES_WSDL_LOCATION;
    private final static WebServiceException BSSANCOACTUALIZACIONMETADATOSPODERES_EXCEPTION;
    private final static QName BSSANCOACTUALIZACIONMETADATOSPODERES_QNAME = new QName("https://www.supernotariado.gov.co/services/bachue/co/actualizacionmetadatospoderes/v1", "BS_SAN_CO_ActualizacionMetadatosPoderes");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/consultor/Documents/NetbeansProjects82/ClienteOWCC/src/conf/xml-resources/web-services/BeanActualizarMetaPoder/wsdl/BS_SAN_CO_ActualizacionMetadatosPoderes.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BSSANCOACTUALIZACIONMETADATOSPODERES_WSDL_LOCATION = url;
        BSSANCOACTUALIZACIONMETADATOSPODERES_EXCEPTION = e;
    }

    public BSSANCOActualizacionMetadatosPoderes_Service() {
        super(__getWsdlLocation(), BSSANCOACTUALIZACIONMETADATOSPODERES_QNAME);
    }

    public BSSANCOActualizacionMetadatosPoderes_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), BSSANCOACTUALIZACIONMETADATOSPODERES_QNAME, features);
    }

    public BSSANCOActualizacionMetadatosPoderes_Service(URL wsdlLocation) {
        super(wsdlLocation, BSSANCOACTUALIZACIONMETADATOSPODERES_QNAME);
    }

    public BSSANCOActualizacionMetadatosPoderes_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BSSANCOACTUALIZACIONMETADATOSPODERES_QNAME, features);
    }

    public BSSANCOActualizacionMetadatosPoderes_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BSSANCOActualizacionMetadatosPoderes_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BSSANCOActualizacionMetadatosPoderes
     */
    @WebEndpoint(name = "BS_SAN_CO_ActualizacionMetadatosPoderesPort")
    public BSSANCOActualizacionMetadatosPoderes getBSSANCOActualizacionMetadatosPoderesPort() {
        return super.getPort(new QName("https://www.supernotariado.gov.co/services/bachue/co/actualizacionmetadatospoderes/v1", "BS_SAN_CO_ActualizacionMetadatosPoderesPort"), BSSANCOActualizacionMetadatosPoderes.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BSSANCOActualizacionMetadatosPoderes
     */
    @WebEndpoint(name = "BS_SAN_CO_ActualizacionMetadatosPoderesPort")
    public BSSANCOActualizacionMetadatosPoderes getBSSANCOActualizacionMetadatosPoderesPort(WebServiceFeature... features) {
        return super.getPort(new QName("https://www.supernotariado.gov.co/services/bachue/co/actualizacionmetadatospoderes/v1", "BS_SAN_CO_ActualizacionMetadatosPoderesPort"), BSSANCOActualizacionMetadatosPoderes.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BSSANCOACTUALIZACIONMETADATOSPODERES_EXCEPTION!= null) {
            throw BSSANCOACTUALIZACIONMETADATOSPODERES_EXCEPTION;
        }
        return BSSANCOACTUALIZACIONMETADATOSPODERES_WSDL_LOCATION;
    }

}
