<?xml version="1.0" encoding="UTF-8" ?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
  xmlns:bachue="https://www.supernotariado.gov.co/services/bachue/co/relacionesdocumento/v1"
  targetNamespace="https://www.supernotariado.gov.co/services/bachue/co/relacionesdocumento/v1"
  xmlns:bachue1="https://www.supernotariado.gov.co/schemas/bachue/co/relacionesdocumento/relacionardocumento/v1"
  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/">
	<wsdl:types>
		<schema xmlns="http://www.w3.org/2001/XMLSchema">
			<import namespace="https://www.supernotariado.gov.co/schemas/bachue/co/relacionesdocumento/relacionardocumento/v1" schemaLocation="Schemas/Legacy/CO_RD_RelacionarDocumento.xsd" />
		</schema>
	</wsdl:types>

	<wsdl:message name="RelacionarDocumento_Request">
		<wsdl:part name="entrada" element="bachue1:entradaRelacionarDocumento"/>
	</wsdl:message>
	<wsdl:message name="RelacionarDocumento_Response">
		<wsdl:part name="salida" element="bachue1:salidaRelacionarDocumento"/>
	</wsdl:message>

	<wsdl:portType name="SUT_CO_RelacionesDocumento">
		<wsdl:operation name="RelacionarDocumento">
			<wsdl:input message="bachue:RelacionarDocumento_Request"/>
			<wsdl:output message="bachue:RelacionarDocumento_Response"/>
		</wsdl:operation>
	</wsdl:portType>
 <wsdl:binding name="SUT_CO_RelacionesDocumentoSOAP12Binding" type="bachue:SUT_CO_RelacionesDocumento">
  <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
  <wsdl:operation name="RelacionarDocumento">
   <soap12:operation style="document"
                     soapAction="https://www.supernotariado.gov.co/services/bachue/co/relacionesdocumento/v1/RelacionarDocumento"/>
   <wsdl:input>
    <soap12:body use="literal" parts="entrada"/>
   </wsdl:input>
   <wsdl:output>
    <soap12:body use="literal" parts="salida"/>
   </wsdl:output>
  </wsdl:operation>
 </wsdl:binding>
 <wsdl:service name="SUT_CO_RelacionesDocumento">
  <wsdl:port name="SUT_CO_RelacionesDocumentoPort" binding="bachue:SUT_CO_RelacionesDocumentoSOAP12Binding">
   <soap12:address location="http://www.example.com"/>
  </wsdl:port>
 </wsdl:service>
</wsdl:definitions>