/*
 *
 */

package https.www_supernotariado_gov_co.services.bachue.co.creadorturno.v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import https.www_supernotariado_gov_co.schemas.bachue.co.creadorturno.crearturno.v1.ObjectFactory;
import https.www_supernotariado_gov_co.schemas.bachue.co.creadorturno.crearturno.v1.TipoEntradaCrearTurno;
import https.www_supernotariado_gov_co.schemas.bachue.co.creadorturno.crearturno.v1.TipoSalidaCrearTurno;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150120.1832
 * Generated source version: 2.2
 *
 */
@WebService(name = "SUT_CO_CreadorTurno", targetNamespace = "https://www.supernotariado.gov.co/services/bachue/co/creadorturno/v1")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SUTCOCreadorTurno {


    /**
     * Crear turno.
     *
     * @param entrada the entrada
     * @return     returns https.www_supernotariado_gov_co.schemas.bachue.co.creadorturno.crearturno.v1.TipoSalidaCrearTurno
     */
    @WebMethod(operationName = "CrearTurno", action = "https://www.supernotariado.gov.co/services/bachue/co/creadorturno/v1/CrearTurno")
    @WebResult(name = "salidaCrearTurno", targetNamespace = "https://www.supernotariado.gov.co/schemas/bachue/co/creadorturno/crearturno/v1", partName = "salida")
    public TipoSalidaCrearTurno crearTurno(
        @WebParam(name = "entradaCrearTurno", targetNamespace = "https://www.supernotariado.gov.co/schemas/bachue/co/creadorturno/crearturno/v1", partName = "entrada")
        TipoEntradaCrearTurno entrada);

}
