/*
 *
 */

package https.www_supernotariado_gov_co.services.bachue.co.creadorturno.v1;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150120.1832
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "SUT_CO_CreadorTurno", targetNamespace = "https://www.supernotariado.gov.co/services/bachue/co/creadorturno/v1", wsdlLocation = "file:/C:/Users/consultor/Documents/NetbeansProjects82/ClienteOWCC/src/conf/xml-resources/web-services/beanCrearTurno/wsdl/BS_SUT_CO_CreadorTurno.wsdl")
public class SUTCOCreadorTurno_Service
    extends Service
{

    /** The Constant SUTCOCREADORTURNO_WSDL_LOCATION. */
    private final static URL SUTCOCREADORTURNO_WSDL_LOCATION;

    /** The Constant SUTCOCREADORTURNO_EXCEPTION. */
    private final static WebServiceException SUTCOCREADORTURNO_EXCEPTION;

    /** The Constant SUTCOCREADORTURNO_QNAME. */
    private final static QName SUTCOCREADORTURNO_QNAME = new QName("https://www.supernotariado.gov.co/services/bachue/co/creadorturno/v1", "SUT_CO_CreadorTurno");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/consultor/Documents/NetbeansProjects82/ClienteOWCC/src/conf/xml-resources/web-services/beanCrearTurno/wsdl/BS_SUT_CO_CreadorTurno.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SUTCOCREADORTURNO_WSDL_LOCATION = url;
        SUTCOCREADORTURNO_EXCEPTION = e;
    }

    /**
     * Instantiates a new SUTCO creador turno service.
     */
    public SUTCOCreadorTurno_Service() {
        super(__getWsdlLocation(), SUTCOCREADORTURNO_QNAME);
    }

    /**
     * Instantiates a new SUTCO creador turno service.
     *
     * @param features the features
     */
    public SUTCOCreadorTurno_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), SUTCOCREADORTURNO_QNAME, features);
    }

    /**
     * Instantiates a new SUTCO creador turno service.
     *
     * @param wsdlLocation the wsdl location
     */
    public SUTCOCreadorTurno_Service(URL wsdlLocation) {
        super(wsdlLocation, SUTCOCREADORTURNO_QNAME);
    }

    /**
     * Instantiates a new SUTCO creador turno service.
     *
     * @param wsdlLocation the wsdl location
     * @param features the features
     */
    public SUTCOCreadorTurno_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SUTCOCREADORTURNO_QNAME, features);
    }

    /**
     * Instantiates a new SUTCO creador turno service.
     *
     * @param wsdlLocation the wsdl location
     * @param serviceName the service name
     */
    public SUTCOCreadorTurno_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * Instantiates a new SUTCO creador turno service.
     *
     * @param wsdlLocation the wsdl location
     * @param serviceName the service name
     * @param features the features
     */
    public SUTCOCreadorTurno_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * Gets the SUTCO creador turno port.
     *
     * @return     returns SUTCOCreadorTurno
     */
    @WebEndpoint(name = "SUT_CO_CreadorTurnoPort")
    public SUTCOCreadorTurno getSUTCOCreadorTurnoPort() {
        return super.getPort(new QName("https://www.supernotariado.gov.co/services/bachue/co/creadorturno/v1", "SUT_CO_CreadorTurnoPort"), SUTCOCreadorTurno.class);
    }

    /**
     * Gets the SUTCO creador turno port.
     *
     * @param features     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return     returns SUTCOCreadorTurno
     */
    @WebEndpoint(name = "SUT_CO_CreadorTurnoPort")
    public SUTCOCreadorTurno getSUTCOCreadorTurnoPort(WebServiceFeature... features) {
        return super.getPort(new QName("https://www.supernotariado.gov.co/services/bachue/co/creadorturno/v1", "SUT_CO_CreadorTurnoPort"), SUTCOCreadorTurno.class, features);
    }

    /**
     * Gets the wsdl location.
     *
     * @return the url
     */
    private static URL __getWsdlLocation() {
        if (SUTCOCREADORTURNO_EXCEPTION!= null) {
            throw SUTCOCREADORTURNO_EXCEPTION;
        }
        return SUTCOCREADORTURNO_WSDL_LOCATION;
    }

}
